### ISSUE TITLE
添加战地2042信息查询功能

### ISSUE THREAD

**Issue by xi-yue-233** [050644zf/nonebot-plugin-bfchat#1]

**Comment by 050644zf** [comment]
我也想弄，但gametools的API目前对2042支持不完整，没有提供类似的接口
如果有找到合适的API可以重开issue

**Comment by 050644zf** [comment]
gametools的2042 API已上线查询战绩功能，目前来看2042需要显示的内容更多，需要对显示模板做出更多的调整

https://api.gametools.network/docs#/Battlefield%202042/bf2042stats_bf2042_stats__get 

更新进度将在这个issue中跟进

**Comment by xi-yue-233** [comment]
我焯，我前天才成功把battlefieldtracker爬下来自己写了一个查2042的…白写了
![Uploading 163a4195b8948eed.png…]()

**Comment by 050644zf** [comment]
> 我焯，我前天才成功把battlefieldtracker爬下来自己写了一个查2042的…白写了

当初也在想用 tracker.gg，但这个东西不时会弹出验证码，不适合给bot用

**Comment by 050644zf** [comment]
已初步验证可行，下面需要添加更多字段及专家、装置等其他的卡片
![Z_ @DHKE6U%%GK0FNIF2O{X](https://user-images.githubusercontent.com/30611816/214292696-1bad3b1b-6cbb-4f92-bbf7-1eb6d152a4ce.PNG)

API还在WIP，没加载出来的图是API问题：
```json
    {
      "type": "Land",
      "vehicleName": "T28",
      "image": "",
      "id": "sur_land_t28",
      "kills": 51,
      "killsPerMinute": 1.06
}
```

新版本已推送到github，暂未发包，可以通过clone到本地体验，需要在机器人的`pyproject.toml`中配置`plugin_dirs`到本仓库目录并在`plugins`中移除本包的导入

**Comment by 050644zf** [comment]
目前来看这个API可能是由于开发中原因，请求时间要挺久的，而且头像需要额外请求一次，所以会挺卡的

**Comment by xi-yue-233** [comment]
![81639F34292F654C1A925A4671F994B7](https://user-images.githubusercontent.com/58218656/214304770-b1814347-a8d8-419e-8f86-d9eacc7299cd.png)
我之前自己写的，但是没有图

**Comment by 050644zf** [comment]
> ![81639F34292F654C1A925A4671F994B7](https://user-images.githubusercontent.com/58218656/214304770-b1814347-a8d8-419e-8f86-d9eacc7299cd.png)
> 我之前自己写的，但是没有图

可以的，现在只需要补些字段以及专家、装置卡片就好

这个版本优化了一下文件结构，不同游戏的代码已经分开了。如果您方便，可以提交一个PR，我最近还不是挺有空的

**Comment by xi-yue-233** [comment]
在新版本的基础上我加入了专家信息，不知道后续还需不需要加入装备那些信息。
如果可以的话稍后我提交一个pr
![429194328-4144104964-C6F0F0B217A32B0F89C4E67268076435](https://user-images.githubusercontent.com/58218656/226698611-9f524e05-68ed-40bf-913a-9b5d8d4ef000.png)
![429194328-307473970-CF099CC5E1E5B6CA6A15B572C17C467B](https://user-images.githubusercontent.com/58218656/226698635-dc3aeae9-0751-4bf3-8b2a-bceb3f57dcc7.png)

**Comment by 050644zf** [comment]
2042查询功能已在v0.3.0版本发布，感谢 @xi-yue-233 的PR #6
