### ISSUE TITLE
NB加载成功，CQHTTP也接收到消息，但是不返回查询结果

### ISSUE THREAD

**Issue by Alessandro597** [050644zf/nonebot-plugin-bfchat#10]
请问我为什么 NB加载成功，CQHTTP也接收到消息，但是不返回查询结果，请求您帮忙，谢谢了！

**Comment by 050644zf** [comment]
报错看一下

**Comment by Alessandro597** [comment]
我配置加载配置好了，也按指令输入，但是没反应，请求您帮忙，谢谢了！
![image](https://github.com/050644zf/nonebot-plugin-bfchat/assets/135231191/9359ba6a-3eae-4af4-a937-2c7d97670576)
![image](https://github.com/050644zf/nonebot-plugin-bfchat/assets/135231191/9c7d7ddf-1096-4928-9a58-27daa8a40937)
![image](https://github.com/050644zf/nonebot-plugin-bfchat/assets/135231191/99534be5-89e9-46ee-9c5a-7e2d51d32e5b)
![image](https://github.com/050644zf/nonebot-plugin-bfchat/assets/135231191/050c1776-ef6b-4264-9975-3ed189d7a075)

**Comment by Alessandro597** [comment]
发现原因了，需要打两个//才可以触发   如  //bf1 xxxx。
请问我需要怎么要才可以修改这个触发指令呢？以及修改weapons 等指令？
