### ISSUE TITLE
请问字体出现乱码怎么解决呀

### ISSUE THREAD

**Issue by a1046700338** [050644zf/nonebot-plugin-bfchat#11]
## 像是这样
![image](https://github.com/050644zf/nonebot-plugin-bfchat/assets/76473954/c7de12bd-cc9a-44c9-a484-56c58b90bbd7)

**Comment by 050644zf** [comment]
您似乎是部署在Linux环境中，请参考并尝试Linux环境中出现中文乱码的相关解决方案。
