### ISSUE TITLE
挂日服、美服加速会导致查询出错

### ISSUE THREAD

**Issue by YouYouLip** [050644zf/nonebot-plugin-bfchat#2]
![image](https://user-images.githubusercontent.com/119958263/210131688-94b026e1-54c9-4901-8bf8-8556441df972.png)
如图 挂亚服节点没事 其他服节点都有事 不能指向性查战绩的时候使用设置的ip或者dns之类的么 加速器应该不是全局代理走向的

**Comment by 050644zf** [comment]
在playwright出现报错应该是htmlrender插件在加载头像、武器等图片资源时或者加载taiwindcss库出错而不是在拉取战绩时出问题。我这边测试的时候在有无代理的情况都运行良好，不是很清楚您的网络环境所以有点难复现。不知道添加代理地址配置能不能帮到你？

如果添加代理地址可行的话：

bfchat使用 [nonebot-plugin-htmlrender](https://github.com/kexue-z/nonebot-plugin-htmlrender) 渲染图片，但htmlrender的接口有点简陋，以至于我只能通过python把所有输出内容硬塞到一个html字符串才能传给htmlrender，而且也没提供代理等配置选项。如果我想要添加代理配置，很可能要抛弃htmlrender，自己改写一个。或者向插件作者发起issue。

**Comment by 050644zf** [comment]
欸不对，我思考了一下，图片没加载成应该只会留空，那更大可能是tailwindcss加载不出来了。

https://github.com/050644zf/nonebot-plugin-bfchat/blob/8ba292db6c5cc4c9ad2b58031b296887be563c63/nonebot_plugin_bfchat/template.html#L5-L12

能否尝试删除上述文件的这几行，看看还会不会报错？

**Comment by YouYouLip** [comment]
> 欸不对，我思考了一下，图片没加载成应该只会留空，那更大可能是tailwindcss加载不出来了。
> 
> https://github.com/050644zf/nonebot-plugin-bfchat/blob/8ba292db6c5cc4c9ad2b58031b296887be563c63/nonebot_plugin_bfchat/template.html#L5
> 
> 能否尝试删除上述文件的这一行，看看还会不会报错？

目测应该是加速器的事 我用了梯子不管是全局代理还是手动代理都可以使用 只不过日本地区的梯子无法加载背景图片 延迟高的梯子会和上面的错误代码一样（应该就是网络问题）我没办法增删文件内容（因为我一直都是poetry shell安装的nb插件） 虚拟环境下安装的nb插件貌似找不到插件文件项（起码我找不到）

**Comment by YouYouLip** [comment]
> 欸不对，我思考了一下，图片没加载成应该只会留空，那更大可能是tailwindcss加载不出来了。
> 
> https://github.com/050644zf/nonebot-plugin-bfchat/blob/8ba292db6c5cc4c9ad2b58031b296887be563c63/nonebot_plugin_bfchat/template.html#L5
> 
> 能否尝试删除上述文件的这一行，看看还会不会报错？

另外github仓库的文件我需要把nonebot_plugin_bfchat里的文件移到根目录下才可被bot检测到不移动该文件夹下的文件到根目录检测不到 会报错再就是删除上一行并不会报错 但是不管是在加速器下还是不在加速器下 都只会显示文字了 并不会有类似图片上的排版

**Comment by 050644zf** [comment]
> 会报错再就是删除上一行并不会报错

那我就大概知道原因了，加速器没能成功代理这个链接，这个是插件所用的CSS样式库，没了排版全没是正常现象，如果我将整个样式库移到本地应该能解决问题，但是图片链接问题应该没法解决

**Comment by 050644zf** [comment]
> 会报错再就是删除上一行并不会报错 但是不管是在加速器下还是不在加速器下 都只会显示文字了 并不会有类似图片上的排版

那我知道问题了，就是加速器没能成功代理这个链接，这个是插件所使用的css样式库，没了就没有排版了。我会尝试推送一个版本将其变为本地文件，应该能解决问题

至于背景图片问题应该没法解决，我现在是用的图床链接，你可以在下面的代码中替换为任意你喜欢的图片链接

https://github.com/050644zf/nonebot-plugin-bfchat/blob/8ba292db6c5cc4c9ad2b58031b296887be563c63/nonebot_plugin_bfchat/template.py#L8-L10

未来视情况我会将其转化为一个配置项

> 我没办法增删文件内容（因为我一直都是poetry shell安装的nb插件） 虚拟环境下安装的nb插件貌似找不到插件文件项（起码我找不到）

这里似乎有方法可以找到虚拟环境的目录： https://github.com/python-poetry/poetry/issues/106 ，或者用everything之类的软件应该都能找

>另外github仓库的文件我需要把nonebot_plugin_bfchat里的文件移到根目录下才可被bot检测到不移动该文件夹下的文件到根目录检测不到 

github仓库包含了打包模块的额外文件，实际主要代码在nonebot_plugin_bfchat下

如果你在plugins目录下clone了整个文件夹，你可以在机器人的 `pyproject.toml` 的 `[tool.nonebot]` 项下添加

```
plugin_dirs = ["plugins/nonebot-plugin-bfchat"]
```

来正确导入

**Comment by YouYouLip** [comment]
> > 会报错再就是删除上一行并不会报错 但是不管是在加速器下还是不在加速器下 都只会显示文字了 并不会有类似图片上的排版
> 
> 那我知道问题了，就是加速器没能成功代理这个链接，这个是插件所使用的css样式库，没了就没有排版了。我会尝试推送一个版本将其变为本地文件，应该能解决问题
> 
> 至于背景图片问题应该没法解决，我现在是用的图床链接，你可以在下面的代码中替换为任意你喜欢的图片链接
> 
> https://github.com/050644zf/nonebot-plugin-bfchat/blob/8ba292db6c5cc4c9ad2b58031b296887be563c63/nonebot_plugin_bfchat/template.py#L8-L10
> 
> 未来视情况我会将其转化为一个配置项
> 
> > 我没办法增删文件内容（因为我一直都是poetry shell安装的nb插件） 虚拟环境下安装的nb插件貌似找不到插件文件项（起码我找不到）
> 
> 这里似乎有方法可以找到虚拟环境的目录： [python-poetry/poetry#106](https://github.com/python-poetry/poetry/issues/106) ，或者用everything之类的软件应该都能找
> 
> > 另外github仓库的文件我需要把nonebot_plugin_bfchat里的文件移到根目录下才可被bot检测到不移动该文件夹下的文件到根目录检测不到
> 
> GitHub仓库包含了打包模块的额外文件，实际主要代码在nonebot_plugin_bfchat下
> 
> 如果你在plugins目录下clone了整个文件夹，你可以在机器人的 的 项下添加`pyproject.toml``[tool.nonebot]`
> 
> ```
> plugin_dirs = ["plugins/nonebot-plugin-bfchat"]
> ```
> 
> 来正确导入

嗯嗯 感谢 我已经找到了虚拟环境下的配置并且找到了您的插件配置文件 问题应该解决了（加速器没能代理上这个这个链接 肯定是加速器烂因为我用的是 大名鼎鼎的雷神减速器）

**Comment by 050644zf** [comment]
刚试了下把css框架直接放进去还是有点问题，等以后如果有类似问题再试了。

> （加速器没能代理上这个这个链接 肯定是加速器烂因为我用的是 大名鼎鼎的雷神减速器）

哈哈我也用的雷神，碍不住便宜。

机器人有条件最好还是不要部署在主力机上以避免网络波动。祝您使用愉快。
