### ISSUE TITLE
背景图片获取能不能做成本地获取

### ISSUE THREAD

**Issue by YouYouLip** [050644zf/nonebot-plugin-bfchat#3]
我尝试了指向在您上次提供的替换背景图片代码位置 但是貌似只支持http网页获取下载（？）不支持本地图片获取 我尝试指向文件夹 但是没有反应（http网址下的容易寄 而且只能显示上半部分替换的图片很难调一个对得上的）所以有办法做成指向本地文件夹嘛？ 但是playwright就是通过浏览器获取图片的一个插件底层，所以我感觉 应该是比较难指向的（？）有可能做成背景图片本地指向获取吗 或者获取指向文件夹生成战绩的时候随机从文件夹内挑一张

**Comment by 050644zf** [comment]
确实比较难搞成本地的，一个比较可行的方式是使用本地的web server
例如在everything软件中就提供了一个，能将本地文件系统映射到localhost (127.0.0.1) 上：
![image](https://user-images.githubusercontent.com/30611816/211033401-daccbc9c-5f11-4651-9cc8-fd34aee6594e.png)
你可以在配置好服务器后访问对应网址，找到需要的图片，把链接粘贴进代码中

**Comment by YouYouLip** [comment]
事实证明 其实也不用这么麻烦 因为我发现从b站上也可以 只要去专栏那么 复制图像链接 即便是https://i0.hdslb.com/bfs/article/9e92c2cf06eea1988fc0b55d0b36f584f23181ef.jpg@942w_1266h_progressive.webp这样格式的也可以贴在该插件的背景图上，（这样说来我岂不是可以忽略自创http 用b站给我当背景图）
![2907336149-3280397173-F74269EBF2C26AA009CB0B9AF7FE6696](https://user-images.githubusercontent.com/119958263/221391684-f60489d9-a6d5-4349-8486-d7be95c6214c.png)

**Comment by YouYouLip** [comment]
> 事实证明 其实也不用这么麻烦 因为我发现从b站上也可以 只要去专栏那么 复制图像链接 即便是 https://i0.hdslb.com/bfs/article/9e92c2cf06eea1988fc0b55d0b36f584f23181ef.jpg@942w_1266h_progressive.webp 这样格式的也可以贴在该插件的背景图上，（这样说来我岂不是可以忽略自创HTTP 用b站给我当背景图） ![2907336149-3280397173-F74269EBF2C26AA009CB0B9AF7FE6696](https://user-images.githubusercontent.com/119958263/221391684-f60489d9-a6d5-4349-8486-d7be95c6214c.png)

突然想到了一句话，是n网还是Steam的，感谢Steam wallpaper engine 给我当垃圾存储站，把我十几年的垃圾东西存储在上面

**Comment by YouYouLip** [comment]
突然想到了一句话 是n网还是Steam的 “感谢Steam的 wallpaper engine 给我当云空间存储了几年的垃圾东西”

**Comment by YouYouLip** [comment]
不过 背景图不能半透明或者全透明实在太可惜了（悲）
