### ISSUE TITLE
请问后续有无接入bfban/bfeac的举报功能呢？

### ISSUE THREAD

**Issue by zzcqie666** [050644zf/nonebot-plugin-bfchat#5]
期待群内举报

**Comment by 050644zf** [comment]
bfban API: https://bfban.gametools.network/docs/
bfeac API 未能找到

我认为该功能不是很有必要，bfban已经提供了很直观的界面进行举报，而且提交举报材料还是在网页方便。

如果有实现能力欢迎提交PR。
