### ISSUE TITLE
请问作者，插件可以用在QQ频道吗？

### ISSUE THREAD

**Issue by zhom240** [050644zf/nonebot-plugin-bfchat#9]
nonebot插件商店有一个gocq频道补丁，不知道有没有适配呢

或者我应该在哪里可以更方便的联系到你？

**Comment by zhom240** [comment]
作者你好，2404550754.这是我的QQ号

**Comment by 050644zf** [comment]
我这边还没有可以访问频道的机器人账号，而且看起来这个[补丁](https://github.com/mnixry/nonebot-plugin-guild-patch) 还在开发中，由于时间关系恕不能添加该功能。

当然，如果您方便的话可以fork本repo尝试添加并提交一个PR，感谢您的支持！
